2017-03-27 23:14:18,532 INFO     BEGIN
2017-03-27 23:14:18,532 INFO     struct {
    trainer:
        n_rollout_batch: 100
        max_rollout_len: 100
        name: 'CurriculumTrainer'
        switch_iter: 10000
        n_update: 100
        resample_every: 5
        log_each_task: False
        parallel: 4
    name: 'train'
    train: True
    eval: False
    objective:
        discount: 0.9
        entropy_bonus: 0.01
        step_size: 0
        n_train_batch: 4000
    world:
        n_train: 1000
        test_fold: 'val'
        name: 'ShurdlurnWorld'
        train_fold: 'train'
        n_test: 1000
    model:
        critic:
            type: 'linear'
            by_task: True
        intrinsic_bonus: 0
        controller:
            n_hidden: 128
            use_task: True
            gumbel: True
            use_ling: False
            type: 'att'
            update: 'discrete'
            n_embed: 64
        actor:
            type: 'discrete'
            n_hidden: [128, 128]
            ret_bias: -3
        name: 'ReprModel'
    guide:
        name: 'SketchGuide'
    experiment_dir: 'experiments/train'
}
2017-03-27 23:14:19,697 WARNING  unable to process utt from AXPP6I0W11RTS
2017-03-27 23:14:19,698 WARNING  unable to process utt from AXPP6I0W11RTS
2017-03-27 23:14:19,698 WARNING  unable to process utt from AXPP6I0W11RTS
2017-03-27 23:14:21,599 WARNING  unable to parse K8rjiTQYjD5
2017-03-27 23:14:22,417 ERROR    Uncaught exception: hasattr expected 2 arguments, got 1
None
2017-03-27 23:14:22,417 ERROR    Traceback (most recent call last):

  File "main.py", line 67, in <module>
    main()

  File "main.py", line 22, in main
    world = worlds.load(config)

  File "/home/ubuntu/phint/worlds/__init__.py", line 13, in load
    return cls(config)

  File "/home/ubuntu/phint/worlds/shurdlurn/__init__.py", line 108, in __init__
    if hasattr(self.config.world.n_train):

TypeError: hasattr expected 2 arguments, got 1
None
